# Generated by Django 4.2.1 on 2023-05-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RTIMonitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={
                "permissions": (("can_view_analytics", "Allowed to view analytics"),)
            },
        ),
    ]
