# Generated by Django 4.2.1 on 2023-05-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RTIMonitor", "0002_alter_incident_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CFSDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="incident",
            name="id_cfsdistrict",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RTIMonitor.cfsdistrict",
            ),
        ),
    ]
